sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t kwangsoo/docker-react-app -f DockerFile.dev .

script: 
  - docker run -e CI=true kwangsoo/docker-react-app npm run test -- --coverage

after_install: 
  - echo "end creating an image with dockerfile"